/* Plugin Template generated by Pawn Studio */

#include <sourcemod>

public Plugin:myinfo = 
{
	name = "vLanService",
	author = "唔開Mon打機既印度人",
	description = "<- Description ->",
	version = "1.0",
	url = "<- URL ->"
}
new String:List[250][32];
public client2vlan(client, String:Name[], size){

	new ip;
	decl String:IP[32]="";
	GetClientIP(client, IP, sizeof(IP), true);
	ip = StringToInt(IP[11]);
	ReadNameList();

	Format(Name, size, "%s", List[ip-1]);
	
}

ReadNameList(){

new String:path[PLATFORM_MAX_PATH];
BuildPath(Path_SM, path, sizeof(path), "configs/IndianSeries/nameList.txt");
new Handle:file = OpenFile(path, "r");
if(file == INVALID_HANDLE){return;}
new String:dataTemp[3000]="";

while(!IsEndOfFile(file) && ReadFileLine(file, dataTemp, sizeof(dataTemp))){
	
	ExplodeString(dataTemp, ";", List, sizeof(List), sizeof(List[]));

}
CloseHandle(file);
}